services:
  - type: web
    name: campusai
    runtime: docker
    repo: https://github.com/harshithreddy10/campus_ai
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: llama3:latest
